export const tripsData = [
    {
      "id": "1",
      "from": "istanbul",
      "to": "ankara",
      "time": "19:30",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": false, "sex": "" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": true, "sex": "female" },
        { "no": 12, "reserved": false, "sex": "" },
        { "no": 13, "reserved": false, "sex": "" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "2",
      "from": "ankara",
      "to": "istanbul",
      "time": "18:00",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": true, "sex": "male" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": true, "sex": "female" },
        { "no": 6, "reserved": false, "sex": "" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": true, "sex": "female" },
        { "no": 13, "reserved": false, "sex": "" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "3",
      "from": "izmir",
      "to": "ankara",
      "time": "19:00",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": false, "sex": "" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": false, "sex": "" },
        { "no": 13, "reserved": true, "sex": "male" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": true, "sex": "female" }
      ]
    },
    {
      "id": "4",
      "from": "ankara",
      "to": "izmir",
      "time": "19:30",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": true, "sex": "male" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": false, "sex": "" },
        { "no": 13, "reserved": false, "sex": "" },
        { "no": 14, "reserved": true, "sex": "male" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": true, "sex": "female" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "5",
      "from": "istanbul",
      "to": "izmir",
      "time": "18:30",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": false, "sex": "" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": false, "sex": "" },
        { "no": 13, "reserved": true, "sex": "male" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "6",
      "from": "izmir",
      "to": "istanbul",
      "time": "21:30",
      "date": "2420-0723--2",
      "seats": [
        { "no": 1, "reserved": true, "sex": "female" },
        { "no": 2, "reserved": true, "sex": "female" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": false, "sex": "" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": true, "sex": "male" },
        { "no": 13, "reserved": false, "sex": "" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": true, "sex": "male" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "7",
      "from": "ankara",
      "to": "istanbul",
      "time": "17:45",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": true, "sex": "male" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": true, "sex": "male" },
        { "no": 13, "reserved": true, "sex": "male" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "8",
      "from": "istanbul",
      "to": "ankara",
      "time": "17:45",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": false, "sex": "" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": false, "sex": "" },
        { "no": 13, "reserved": true, "sex": "female" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "9",
      "from": "izmir",
      "to": "ankara",
      "time": "17:30",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": false, "sex": "" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": true, "sex": "male" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "female" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": false, "sex": "" },
        { "no": 13, "reserved": true, "sex": "male" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "10",
      "from": "izmir",
      "to": "istanbul",
      "time": "20:15",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": false, "sex": "" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": false, "sex": "" },
        { "no": 12, "reserved": true, "sex": "female" },
        { "no": 13, "reserved": true, "sex": "male" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "11",
      "from": "ankara",
      "to": "izmir",
      "time": "21:45",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": true, "sex": "male" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": false, "sex": "" },
        { "no": 4, "reserved": false, "sex": "" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": false, "sex": "" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": true, "sex": "female" },
        { "no": 12, "reserved": true, "sex": "female" },
        { "no": 13, "reserved": true, "sex": "male" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": false, "sex": "" }
      ]
    },
    {
      "id": "12",
      "from": "istanbul",
      "to": "izmir",
      "time": "21:00",
      "date": "2023-07-25",
      "seats": [
        { "no": 1, "reserved": false, "sex": "" },
        { "no": 2, "reserved": true, "sex": "male" },
        { "no": 3, "reserved": true, "sex": "female" },
        { "no": 4, "reserved": true, "sex": "female" },
        { "no": 5, "reserved": false, "sex": "" },
        { "no": 6, "reserved": true, "sex": "female" },
        { "no": 7, "reserved": false, "sex": "" },
        { "no": 8, "reserved": true, "sex": "male" },
        { "no": 9, "reserved": false, "sex": "" },
        { "no": 10, "reserved": true, "sex": "male" },
        { "no": 11, "reserved": true, "sex": "male" },
        { "no": 12, "reserved": false, "sex": "" },
        { "no": 13, "reserved": true, "sex": "female" },
        { "no": 14, "reserved": false, "sex": "" },
        { "no": 15, "reserved": true, "sex": "male" },
        { "no": 16, "reserved": false, "sex": "" },
        { "no": 17, "reserved": true, "sex": "female" },
        { "no": 18, "reserved": false, "sex": "" },
        { "no": 19, "reserved": true, "sex": "female" },
        { "no": 20, "reserved": true, "sex": "male" }
      ]
    }
  ]